### ISSUE TITLE
通过一段代码分析，了解MVC之间相互调用问题？

### ISSUE THREAD

**Issue by UncleYangsir** [UncleYangsir/twob-gif#26]
```
<h3>今日热书</h3> //标题
<hr/> //分割线
<div class="hotbook-wrapper"> //块输出热门标题
     @for((novel, index) <- hotNovels.zipWithIndex) {
         <a class="hotbook" href="@routes.NovelController.chapters(novel.getId())">@novel.getName()</a>
     }
</div>
```
该段代码主要是输出热门的小说名，并且每个小说名附上了各自小说介绍界面；
原理分析：
在代码还没进行前，打开网址：
1、进行传参（@(novels: List[Novel], categories: List[String], category: String, totalCount: Integer, currentPage: Integer, pageCount: Integer, order: String, hotNovels: List[Novel], authors:List[String], tags:List[String])）
-----为了传入参数就要通过routes的编码调用controllers/NovelController中的list方法得到各个参数-------
2、list为了得到各个参数又从数据库调用出所需内容；

最终形成的小请求流程如下：
```
                 V界面发起                C发送请求给M
用户发送访问请求-------------->控制台------------------->数据库收到需求，并返回
   ^       返回到V界面           | ^            将数据返回控制台       |
   |----------------------------|  |-------------------------------- |
```

**Comment by zhonggy** [comment]
流程画的不够好，MV三个主体都没画出来，Model就是Model，不是数据库，View就是View，不是「用户发送访问请求」。

把动作和主体混淆了，会让人很困惑，可以搜搜看看别人是怎么画的。

**Comment by UncleYangsir** [comment]
好的
