### ISSUE TITLE
MVC框架是什么？

### ISSUE THREAD

**Issue by UncleYangsir** [UncleYangsir/twob-gif#33]
- MVC全名是Model View Controller，是模型(model)－视图(view)－控制器(controller)的缩写，一种软件设计典范，用一种业务逻辑、数据、界面显示分离的方法组织代码，将业务逻辑聚集到一个部件里面，在改进和个性化定制界面及用户交互的同时，不需要重新编写业务逻辑。MVC被独特的发展起来用于映射传统的输入、处理和输出功能在一个逻辑的图形化用户界面的结构中。

- 图片解析：

![b03533fa828ba61edbddc04d4034970a304e59a4](https://user-images.githubusercontent.com/30687851/29220461-ad8e60d6-7eed-11e7-8b87-54be5b1a07fd.jpg)

- 链接：https://baike.baidu.com/item/MVC%E6%A1%86%E6%9E%B6/9241230?fr=aladdin&fromid=85990&fromtitle=MVC

**Comment by zhonggy** [comment]
不是「业务问题」
