### ISSUE TITLE
WebSocket是什么？

### ISSUE THREAD

**Issue by UncleYangsir** [UncleYangsir/twob-gif#37]
- WebSocket协议是基于TCP的一种新的网络协议。它实现了浏览器与服务器全双工(full-duplex)通信——允许服务器主动发送信息给客户端。WebSocket通信协议于2011年被IETF定为标准RFC 6455，并被RFC7936所补充规范。
-  原理： 在实现websocket连线过程中，需要通过浏览器发出websocket连线请求，然后服务器发出回应，这个过程通常称为“握手” 。在 WebSocket API，浏览器和服务器只需要做一个握手的动作，然后，浏览器和服务器之间就形成了一条快速通道。两者之间就直接可以数据互相传送。
- 链接：https://baike.baidu.com/item/WebSocket/1953845?fr=aladdin

**Comment by zhonggy** [comment]
WebSocket不是HTTP，是TCP协议
