### ISSUE TITLE
当Linux中内存不足该怎么办？

### ISSUE THREAD

**Issue by UncleYangsir** [UncleYangsir/twob-gif#50]
首先要做的就是查看当前用户的进程：
执行命令:

- $ ps -ef|grep yang（ps -ef是查看当前进程，grep yang指的是限定搜索范围在用户yang内）
![image](https://user-images.githubusercontent.com/30687851/29443755-d1103b8c-840c-11e7-8c12-e5304ab08fa2.png)
第一列是用户名，第二列是pid(进程ID)，第三列是父亲进程(父进程)，从图上看出14682是根源父类，就是自己当前ssh远程登录，不能kill掉;

要想释放内存可以执行命令：
- $ kill 14684
杀死子类进程的pid释放内存

查看当前可用内存：
从应用程序的角度来说，可用内存 = 系统free memory + buffers + cached.
命令：
free -m
free看系统还剩多少内存
-m表示单位是M
-k，-g是不同的单位
![image](https://user-images.githubusercontent.com/30687851/29444063-24716060-840f-11e7-8238-98215553698e.png)

另外：
输入命令:top
可以查看系统当前进程,再输入命令：M
表示以M为占用内存单位进行倒序排序

附上相关链接：
[linux怎么看进程内存占用以及终止进程](http://blog.csdn.net/wojiaopanpan/article/details/7286430/)
[top命令详细](http://blog.163.com/darlingming@126/blog/static/23421372016739124507/)

**Comment by zhonggy** [comment]
…
XShell只是一个SSH登陆工具，只是个界面，不能说XShell的的内存不足，是Linux的内存不足
